### ISSUE TITLE
Write to file

### ISSUE THREAD

**Issue by peffedu** [UCSB-CS56-Projects/cs56-utilities-cryptography#18]
Issue: Write to a file the plaintext that is to be encrypted, the key, and the encrypted text in one entry. This entry will list the kind of cipher as well and work for the other way around. The file will be written as the program is being run and be finished once the user closes out of the program.

**Comment by alecharrell** [comment]
Approved: ~300 pts A.H.

**Comment by arda-** [comment]
implemented!
