### ISSUE TITLE
Make the GUI look better

### ISSUE THREAD

**Issue by zhanchengqian** [UCSB-CS56-Projects/cs56-utilities-cryptography#32]
1. Make the Encryption/Decryption button into a slide button. (like you can slide it to one end to switch it to Encryption, the other end to switch it to Decryption) 
2. Change the “plaintext” label to “ciphered text” when in decryption mode so notify user about the current mode
3. Change the position where the app shows up from startup

(est. 250 pts)

**Comment by xiaoheh** [comment]
Approved: 200 pts
