### ISSUE TITLE
Brand new GUI (greatly improve the old one) 

### ISSUE THREAD

**Issue by zhanchengqian** [UCSB-CS56-Projects/cs56-utilities-cryptography#39]
Divide the GUI into few columns, the leftmost one has a text box that you can input strings, 
to the right are four key boxes that you can input keys. next to each key box you have a button to generate random keys and also another button to execute. Rightmost is a output text box. 
Basically redesign the old GUI to be a brand new one that makes more sense. 

(est. 250 pts)

**Comment by xiaoheh** [comment]
Approved
