### ISSUE TITLE
Make a new welcome page for the application

### ISSUE THREAD

**Issue by zhanchengqian** [UCSB-CS56-Projects/cs56-utilities-cryptography#45]
Make a new welcome page for the application. For example, when the user opens the app for the first time, he/she will be prompted with this new window "welcome" and in this window, there are several pages. For example the first page is an introduction about the app, and second page would be example of how to use shift cipher, the next page would be how to use affine cipher, and so on... Make sure that this welcome page has a checkbox that says "open me everytime the app starts". If deselected, the welcome page will not appear on the next startup. (estimates 150 points);

**Comment by xiaoheh** [comment]
M16 OK

**Comment by zhanchengqian** [comment]
F16 OK

**Comment by aryamandas** [comment]
F17 OK (50 points)
