### ISSUE TITLE
Add "open" and "folder" buttons

### ISSUE THREAD

**Issue by zhanchengqian** [UCSB-CS56-Projects/cs56-utilities-cryptography#46]
Add "open" button that gives a window that let you choose whatever address you want to save your text file, instead of having you type the address out in "save address". Like those windows that you have when you are trying to upload files as attachment of emails. Also add "folder" button that brings up the save location folder so that user can access it directly in the OS. (estimates 150 points);

**Comment by xiaoheh** [comment]
M16 OK

**Comment by zhanchengqian** [comment]
F16 OK
