### ISSUE TITLE
Fix RSA Cipher algorithm

### ISSUE THREAD

**Issue by marioinfante** [UCSB-CS56-Projects/cs56-utilities-cryptography#56]
Currently the algorithm isn't working. The majority of the algorithm is there, however, it does not work correctly. The cipher is based off of the algorithm that is described in the page linked below:
[RSA (algorithm)](https://simple.wikipedia.org/wiki/RSA_(algorithm))

**Comment by zhanchengqian** [comment]
F16 OK (250 pts)
