### ISSUE TITLE
RSA cipher not on main page and TextFields are too large

### ISSUE THREAD

**Issue by kmahorker** [UCSB-CS56-Projects/cs56-utilities-cryptography#64]
It gets confusing when there is a separate window for the RSA cipher and all the other ciphers are on the main page. The functionality for the RSA cipher should be included on the main page. The text areas are too large and need to be sized down to make the GUI look better and allow for more room for more ciphers. Center Panels need to be refactored to be aligned and relative to one GridBagLayout, not multiple.

(est. 150)

**Comment by aryamandas** [comment]
F17 OK (50 points)
